YCDOCIO-4042: updated Terraform manifest [WIP]
yandex-cloud-examples/yc-mk8s-load-balancer pull request #2
Opened 2024-10-23 14:45 UTC by alena-linki

https://st.yandex-team.ru/YCDOCIO-4042

2024-10-25 04:33 UTC, voloschuk-fedor requested changes

2024-10-25 04:33 UTC, voloschuk-fedor commented on k8s-load-balancer.tf
> +    v4_cidr_blocks = ["0.0.0.0/0"]
Кажется, эта правка некорректна. Взаимодействие тут идет между подами и узлами внутри сети, нет смысла открывать вообще все IP-адреса.

То же относится и к ICMP.

Загляни [вот сюда](https://server-yfm.website.yandexcloud.net/server-yfm-kovalevdanila-YCDOCIO-4019-mk8s-sg-rework/ru/ru/managed-kubernetes/operations/connect/security-groups.html), пожалуйста. На этой странице представлены наиболее актуальные правила для групп безопасности. Задача сейчас в работе, но кажется, что основные правила уже устаканились. 

Коллеги проводят эпичный труд по актуализации правил в задаче 4019. Возможно, тебе стоит заглянуть и в саму задачу, не только в сборку.

2024-10-25 07:41 UTC, alena-linki commented on k8s-load-balancer.tf
> +    v4_cidr_blocks = ["0.0.0.0/0"]
Здесь несколько мыслей, которыми хотела бы поделиться:

- Я внесла правки в плавила группы безопасности, потому что с продовым вариантом нет доступа к приложению, когда разворачиваем внешний балансировщик нагрузки. Как только поправила правила, как сделано в PR, сразу доступ появился. Про это, кстати, есть [примечание в доке](https://server-yfm.website.yandexcloud.net/server-yfm-vorobyova-YCDOCIO-4042-yc/ru/ru/managed-kubernetes/operations/create-load-balancer.html#check-result).
- Точно ли можно ориентироваться на сборку из тикета 4019? Там все еще выясняют, как должно работать. Стремно ориентироваться на работу, не оконченную по технической части.
- В доке Данилы нашла опечатку. Передай ему, пожалуйста (не хочу лезть в тот тикет).

   <img width="749" alt="Screenshot 2024-10-25 at 09 25 07" src="https://github.com/user-attachments/assets/be69e22a-7c47-4a55-8fe2-590a59c99a8c">

2024-10-25 08:15 UTC, alena-linki commented on k8s-load-balancer.tf
> +    v4_cidr_blocks = ["0.0.0.0/0"]
Попробовала развернуть новую инфраструктуру с правилами из сборки Данилы. Использовала CIDR подсети кластера там, где сказано у Данилы. С такими правилами не получается даже создать `Deployment`, не то что получить доступ к приложению.

Ошибка при создании `Deployment`: `Unable to connect to the server: dial tcp 89.169.158.229:443: i/o timeout`

2024-10-29 11:46 UTC, alena-linki commented on k8s-load-balancer.tf
> +    v4_cidr_blocks = ["0.0.0.0/0"]
в итоге вместе разобрались и починили

2026-04-28 13:51 UTC, vnkiryushkin approved these changes

2026-04-28 13:51 UTC, merged